name: CD - Deploy to Kubernetes

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: self-hosted
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set vars
        id: vars
        run: |
          echo "IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/monitor" >> $GITHUB_OUTPUT
          echo "TAG_SHA=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          echo "NAMESPACE=${{ secrets.K8S_NAMESPACE || 'default' }}" >> $GITHUB_OUTPUT

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Configure kubeconfig
        shell: pwsh
        run: |
          $kubeDir = "$env:USERPROFILE\.kube"
          if (!(Test-Path $kubeDir)) {
          New-Item -ItemType Directory -Path $kubeDir | Out-Null
           }
          $configPath = "$kubeDir\config"
          [System.Text.Encoding]::ASCII.GetString([System.Convert]::FromBase64String("${{ secrets.KUBE_CONFIG_DATA }}")) | Out-File -Encoding ascii $configPath
          $env:KUBECONFIG = $configPath
          kubectl version --client

      - name: Criar namespace se necessário
        run: |
          NAMESPACE="${{ steps.vars.outputs.NAMESPACE }}"
          kubectl get ns "$NAMESPACE" >/dev/null 2>&1 || kubectl create ns "$NAMESPACE"

      - name: Aplicar base manifests
        run: |
          NAMESPACE="${{ steps.vars.outputs.NAMESPACE }}"
          for file in k8s/*.yaml; do
            kubectl apply -n "$NAMESPACE" -f "$file" || echo "⚠️ Falha em $file"
          done

      - name: Atualizar imagem
        run: |
          NAMESPACE="${{ steps.vars.outputs.NAMESPACE }}"
          IMAGE="${{ steps.vars.outputs.IMAGE }}"
          TAG_SHA="${{ steps.vars.outputs.TAG_SHA }}"
          kubectl set image deployment/monitor monitor="$IMAGE:$TAG_SHA" -n "$NAMESPACE" --record

      - name: Aguardar rollout
        run: |
          NAMESPACE="${{ steps.vars.outputs.NAMESPACE }}"
          kubectl rollout status deployment/monitor -n "$NAMESPACE" --timeout=120s

      - name: Mostrar serviços e pods
        run: |
          NAMESPACE="${{ steps.vars.outputs.NAMESPACE }}"
          kubectl get svc -n "$NAMESPACE"
          kubectl get pods -o wide -n "$NAMESPACE"
