name: CD - Deploy to Minikube

on:
  workflow_run:
    workflows: ["CI - Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production  # permite aprovação manual no GitHub

    steps:
      - name: Configurar kubectl
        run: |
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig

      - name: Substituir porta da aplicação
        run: |
          sed -i 's/{{APP_PORT}}/'"${{ secrets.APP_PORT }}"'/g' k8s/deployment.yaml

      - name: Aplicar manifests no Minikube
        run: |
          NAMESPACE=${{ secrets.K8S_NAMESPACE }}
          if [ -z "$NAMESPACE" ]; then
            NAMESPACE=default
          fi
          kubectl apply -n $NAMESPACE -f k8s/
