name: CD - Deploy to Minikube

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar dependências do Kubernetes
        run: |
          sudo apt-get update
          sudo apt-get install -y conntrack

      - name: Instalar crictl
        run: |
          curl -LO https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.29.0/crictl-v1.29.0-linux-amd64.tar.gz
          sudo tar -C /usr/local/bin -xzf crictl-v1.29.0-linux-amd64.tar.gz

      - name: Instalar Minikube e kubectl
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

      - name: Iniciar Minikube
        run: |
          sudo minikube start --driver=none
          echo "✅ Minikube iniciado"

      - name: Substituir porta da aplicação
        run: |
          sed -i 's/{{APP_PORT}}/'"${{ secrets.APP_PORT }}"'/g' k8s/deployment.yaml || echo "⚠️ Nenhuma substituição feita"

      - name: Criar namespace se necessário
        run: |
          NAMESPACE=${{ secrets.K8S_NAMESPACE }}
          if [ -z "$NAMESPACE" ]; then
            NAMESPACE=default
          fi
          kubectl get ns $NAMESPACE || kubectl create ns $NAMESPACE

      - name: Aplicar manifests no Minikube
        run: |
          NAMESPACE=${{ secrets.K8S_NAMESPACE }}
          if [ -z "$NAMESPACE" ]; then
            NAMESPACE=default
          fi
          kubectl apply -n $NAMESPACE -f k8s/
