name: CI/CD Deploy to Minikube

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout cÃ³digo
      uses: actions/checkout@v3

    - name: Login no Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build da imagem
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/monitor .

    - name: Push da imagem
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/monitor

    - name: Configurar kubectl
      run: |
        echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > kubeconfig
        export KUBECONFIG=$PWD/kubeconfig

    - name: Aplicar manifests no Minikube
      run: kubectl apply -f k8s/
